name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: run and test alerter
        run: npx mocha "alerterTest.js"
        
      - name: run and misaligned
        run: npx mocha "misalignedTest.js"  
        
      - name: run and test tshirts
        run: npx mocha "tshirtsTest.js"
        

